### ISSUE TITLE
Restart times offset

### ISSUE THREAD

**Issue by AndyHoggANU** [COSIMA/access-om2#43] opened 2017-09-21 23:37 UTC
I am finding a minor problem with my 1° ACCESS-OM2 spinup8 case which might be a pointer to some inconsistencies in the way the coupled model deals with restarts.

In this simulation, I stopped after 182 years, because I wanted to restart from scratch to run another case with massless ice (spinup9). Then I decided to return back to spinup8 (massless ice didn't help the stability problems).  I copied the restart090 file back to the archive and set it running. MOM picked up from day 1 of 183 as expected (although it gave the traditional first message saying it would start from zero):

 ==>Note: Time%Time_init = time stamp at very start of the MOM experiment is given by
yyyy/mm/dd hh:mm:ss =    1/ 1/ 1  0: 0: 0

 ==>Note: Time%model_time = time stamp at start of this leg of the MOM experiment is
yyyy/mm/dd hh:mm:ss =  183/ 1/ 1  0: 0: 0

but MATM did actually return to time zero:

MATM (init_calendar) idate0 =        10101

MATM istep1:        47    idate:     10102    sec:         0

What this means is that I have CICE output with a date starting from zero, and which has a different date from the MOM output of the same run! It may make analysis a little tricky.

I'm not yet sure why this has happened -- maybe I should have restarted in a different way, but I think it is important to ensure consistent dates between outputs from the different component models ...

**Comment by nicjhan** [comment] 2017-09-21 23:58
It's good that you were observant and picked this up. We need better automatic date checking in the model.

**Comment by marshallward** [comment] 2017-09-29 10:04
@AndyHoggANU Still not clear on this MATM restart issue - is this something that can be fixed by payu?  Should we try to fix it before doing a 0.8 payu tag?  Or can we just leave #43 resolved?

**Comment by nicjhan** [comment] 2017-10-05 04:41
I have reproduced this and see two problems: 

1. MATM gets the date wrong when restarting. It just starts back at the beginning of the year.  This needs to be fixed but should not be a problem with existing 'branch' runs. 
2. CICE also gets the restart date wrong also which means that it doesn't use the correct restart. 

It looks like the existing branched runs may be questionable given point 2 above. 

For example a regular continuation run will give output something like: 

 XXX: org restart file =>
 ./RESTART/iced.0017-01-01-00000.nc

whereas a branched run doesn't have this. The ice model is starting from scratch.

**Comment by ofa001** [comment] 2017-10-05 09:44
If the ice model is starting from scratch it sounds like you don’t have the right setiings in the namelist it should pick up the restart file if it knows it is a continuing run,  you need to have  a different namelist for the second year etc.

Siobhan

**Comment by AndyHoggANU** [comment] 2017-10-05 10:13
The thing that I don't understand is - why does it do this for branched runs, but not for normal runs? The restart information should be the same, shouldn't it?

**Comment by StephenGriffies** [comment] 2017-10-05 11:02
Regarding @ofa001 comment:

A different namelist for the second stage?  Why should  CICE need to change namelist after the first initialization run?  Puzzled.

**Comment by nicjhan** [comment] 2017-10-05 22:22
OK, I have found the problem here. Presently payu uses both the prior restart and the prior output to setup the new 'branched' run. 

So @AndyHoggANU you need to not only copy over the restartXXX dir into the new experiment archive but also the outputXXX (where XXX is the same number for both). 

One approach would be to add an error case to Payu so that it  exits if the restart is there but not the corresponding prior output. This will be a temporary fix however. I need to make sure the model can be restarted from the restart alone.

**Comment by marshallward** [comment] 2017-10-05 22:34
If the driver is looking in the outputXXX directory for any if its input fields, then I'd definitely consider that to be a Payu bug.

**Comment by AndyHoggANU** [comment] 2017-10-05 22:49
So, firstly, this makes complete sense.
I agree with Marshall that it is a bug ... did you finalise 0.8 yet? If not, maybe we should wait until we can fix the bug before finalising?
Until that happens, I think we will keep moving forward with a workaround.

**Comment by marshallward** [comment] 2017-10-05 22:53
No, have not done the 0.8 tag yet, let's try to fix this one.

**Comment by nicjhan** [comment] 2017-10-06 04:34
OK, I'll send a pull request with the fix.

**Comment by aekiss** [comment] 2017-11-06 09:55
Has this issue been fixed now that Payu 0.8 is on raijin? (should it be closed?)

**Comment by AndyHoggANU** [comment] 2017-11-06 21:23
Good question. I think we only have a workaround (which involves ensuring that both output and restart files from the last run are retained in the archive).  If anyone knows differently, please chime in.

**Comment by nicjhan** [comment] 2017-11-06 22:57
Yes, that's correct, we only have a workaround at this point.

**Comment by nicjhan** [comment] 2017-11-09 04:00
This will be fixed by https://github.com/marshallward/payu/pull/88

**Comment by marshallward** [comment] 2017-11-09 04:14
I've merged this, but do I need to update `/apps/payu` now?

If so, I think we need to talk about a better release strategy.  I think you guys ought to at least trial things for a week in `/projects/v45/payu/dev` before updating `/apps`.

**Comment by aidanheerdegen** [comment] 2017-11-09 04:32
Agreed.

I have updated `payu/dev` in `/projects/v45` to the latest master

**Comment by aekiss** [comment] 2017-11-17 22:41
I get an error in `payu sweep` with `/projects/v45/payu/dev`:
```
[aek156@raijin6 ~]$ cd /short/v45/aek156/access-om2/control/025deg_jra55_ryf/
[aek156@raijin6 025deg_jra55_ryf]$ module load payu/dev
[aek156@raijin6 025deg_jra55_ryf]$ payu sweep
Traceback (most recent call last):
  File "/projects/v45/apps/payu/dev/bin/payu", line 8, in <module>
    cli.parse()
  File "/projects/v45/apps/payu/dev/lib/payu/cli.py", line 39, in parse
    subcmds = [importlib.import_module(mod) for mod in modnames]
  File "/apps/python/2.7.6/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/projects/v45/apps/payu/dev/lib/payu/subcommands/archive_cmd.py", line 3, in <module>
    from payu.experiment import Experiment
  File "/projects/v45/apps/payu/dev/lib/payu/experiment.py", line 28, in <module>
    from payu.runlog import Runlog
  File "/projects/v45/apps/payu/dev/lib/payu/runlog.py", line 18, in <module>
    import requests
ImportError: No module named requests
```

**Comment by aidanheerdegen** [comment] 2017-11-17 23:07
Sorry, the dependencies weren't installed correctly. I've fixed it, but let me know if you still have issues.

**Comment by aekiss** [comment] 2017-11-18 01:43
thanks Aidan, all good now

**Comment by nichannah** [comment] 2019-09-23 01:52
I imagine that this is fixed since we are no longer using MATM and many Payu changes.

**Closed by nichannah** 2019-09-23 01:52 UTC
